# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChoicePanel.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChoicePanel(object):
    def setupUi(self, ChoicePanel):
        ChoicePanel.setObjectName("ChoicePanel")
        ChoicePanel.resize(1053, 103)
        self.centralwidget = QtWidgets.QWidget(ChoicePanel)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pinyinPanel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pinyinPanel.setFont(font)
        self.pinyinPanel.setText("")
        self.pinyinPanel.setObjectName("pinyinPanel")
        self.verticalLayout.addWidget(self.pinyinPanel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choice1_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choice1_btn.sizePolicy().hasHeightForWidth())
        self.choice1_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.choice1_btn.setFont(font)
        self.choice1_btn.setMouseTracking(True)
        self.choice1_btn.setFlat(True)
        self.choice1_btn.setObjectName("choice1_btn")
        self.horizontalLayout.addWidget(self.choice1_btn)
        self.choice2_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choice2_btn.sizePolicy().hasHeightForWidth())
        self.choice2_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.choice2_btn.setFont(font)
        self.choice2_btn.setMouseTracking(True)
        self.choice2_btn.setFlat(True)
        self.choice2_btn.setObjectName("choice2_btn")
        self.horizontalLayout.addWidget(self.choice2_btn)
        self.choice3_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choice3_btn.sizePolicy().hasHeightForWidth())
        self.choice3_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.choice3_btn.setFont(font)
        self.choice3_btn.setMouseTracking(True)
        self.choice3_btn.setFlat(True)
        self.choice3_btn.setObjectName("choice3_btn")
        self.horizontalLayout.addWidget(self.choice3_btn)
        self.choice4_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choice4_btn.sizePolicy().hasHeightForWidth())
        self.choice4_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.choice4_btn.setFont(font)
        self.choice4_btn.setMouseTracking(True)
        self.choice4_btn.setFlat(True)
        self.choice4_btn.setObjectName("choice4_btn")
        self.horizontalLayout.addWidget(self.choice4_btn)
        self.choice5_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choice5_btn.sizePolicy().hasHeightForWidth())
        self.choice5_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.choice5_btn.setFont(font)
        self.choice5_btn.setMouseTracking(True)
        self.choice5_btn.setFlat(True)
        self.choice5_btn.setObjectName("choice5_btn")
        self.horizontalLayout.addWidget(self.choice5_btn)
        self.choice6_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choice6_btn.sizePolicy().hasHeightForWidth())
        self.choice6_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.choice6_btn.setFont(font)
        self.choice6_btn.setMouseTracking(True)
        self.choice6_btn.setFlat(True)
        self.choice6_btn.setObjectName("choice6_btn")
        self.horizontalLayout.addWidget(self.choice6_btn)
        self.previousGroup_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousGroup_btn.sizePolicy().hasHeightForWidth())
        self.previousGroup_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.previousGroup_btn.setFont(font)
        self.previousGroup_btn.setMouseTracking(True)
        self.previousGroup_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/leftTriangle.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousGroup_btn.setIcon(icon)
        self.previousGroup_btn.setFlat(True)
        self.previousGroup_btn.setObjectName("previousGroup_btn")
        self.horizontalLayout.addWidget(self.previousGroup_btn)
        self.nextGroup_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextGroup_btn.sizePolicy().hasHeightForWidth())
        self.nextGroup_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nextGroup_btn.setFont(font)
        self.nextGroup_btn.setMouseTracking(True)
        self.nextGroup_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/rightTriangle.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextGroup_btn.setIcon(icon1)
        self.nextGroup_btn.setFlat(True)
        self.nextGroup_btn.setObjectName("nextGroup_btn")
        self.horizontalLayout.addWidget(self.nextGroup_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        ChoicePanel.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChoicePanel)
        QtCore.QMetaObject.connectSlotsByName(ChoicePanel)

    def retranslateUi(self, ChoicePanel):
        _translate = QtCore.QCoreApplication.translate
        ChoicePanel.setWindowTitle(_translate("ChoicePanel", "ChoicePanel"))
        self.choice1_btn.setText(_translate("ChoicePanel", "1"))
        self.choice2_btn.setText(_translate("ChoicePanel", "2"))
        self.choice3_btn.setText(_translate("ChoicePanel", "3"))
        self.choice4_btn.setText(_translate("ChoicePanel", "4"))
        self.choice5_btn.setText(_translate("ChoicePanel", "5"))
        self.choice6_btn.setText(_translate("ChoicePanel", "6"))

