# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Homepage.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Homepage(object):
    def setupUi(self, Homepage):
        Homepage.setObjectName("Homepage")
        Homepage.resize(1056, 759)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Homepage.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Homepage)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hintMsg_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hintMsg_label.setFont(font)
        self.hintMsg_label.setObjectName("hintMsg_label")
        self.verticalLayout_2.addWidget(self.hintMsg_label)
        self.inputPanel = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputPanel.setFont(font)
        self.inputPanel.setObjectName("inputPanel")
        self.verticalLayout_2.addWidget(self.inputPanel)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 20)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clearText_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.clearText_btn.sizePolicy().hasHeightForWidth())
        self.clearText_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.clearText_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearText_btn.setIcon(icon1)
        self.clearText_btn.setIconSize(QtCore.QSize(35, 35))
        self.clearText_btn.setObjectName("clearText_btn")
        self.horizontalLayout_2.addWidget(self.clearText_btn)
        self.copyText_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.copyText_btn.sizePolicy().hasHeightForWidth())
        self.copyText_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.copyText_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/copy.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyText_btn.setIcon(icon2)
        self.copyText_btn.setIconSize(QtCore.QSize(40, 40))
        self.copyText_btn.setObjectName("copyText_btn")
        self.horizontalLayout_2.addWidget(self.copyText_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pinyinInput_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinyinInput_btn.sizePolicy().hasHeightForWidth())
        self.pinyinInput_btn.setSizePolicy(sizePolicy)
        self.pinyinInput_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/keyboard.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pinyinInput_btn.setIcon(icon3)
        self.pinyinInput_btn.setIconSize(QtCore.QSize(150, 150))
        self.pinyinInput_btn.setObjectName("pinyinInput_btn")
        self.horizontalLayout.addWidget(self.pinyinInput_btn)
        self.voiceInput_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voiceInput_btn.sizePolicy().hasHeightForWidth())
        self.voiceInput_btn.setSizePolicy(sizePolicy)
        self.voiceInput_btn.setStyleSheet("QPushButton{border-image: url(:icon/speech_icon.gif);}")
        self.voiceInput_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/silence.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.voiceInput_btn.setIcon(icon4)
        self.voiceInput_btn.setIconSize(QtCore.QSize(150, 150))
        self.voiceInput_btn.setObjectName("voiceInput_btn")
        self.horizontalLayout.addWidget(self.voiceInput_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.hintPanel_tb = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hintPanel_tb.sizePolicy().hasHeightForWidth())
        self.hintPanel_tb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.hintPanel_tb.setFont(font)
        self.hintPanel_tb.setStyleSheet("border-color: rgb(28, 137, 32);")
        self.hintPanel_tb.setObjectName("hintPanel_tb")
        self.verticalLayout.addWidget(self.hintPanel_tb)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout.setStretch(3, 3)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 5)
        self.gridLayout.setColumnMinimumWidth(1, 2)
        Homepage.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(Homepage)
        self.statusBar.setObjectName("statusBar")
        Homepage.setStatusBar(self.statusBar)

        self.retranslateUi(Homepage)
        QtCore.QMetaObject.connectSlotsByName(Homepage)

    def retranslateUi(self, Homepage):
        _translate = QtCore.QCoreApplication.translate
        Homepage.setWindowTitle(_translate("Homepage", "快捷输入法 - 主页"))
        self.hintMsg_label.setText(_translate("Homepage", "请在下方文本框中输入文本:"))
        self.inputPanel.setToolTip(_translate("Homepage", "<html><head/><body><p><span style=\" font-size:12pt;\">输入文字</span></p></body></html>"))
        self.clearText_btn.setText(_translate("Homepage", "清空文本"))
        self.copyText_btn.setText(_translate("Homepage", "复制文本"))
        self.pinyinInput_btn.setToolTip(_translate("Homepage", "<html><head/><body><p><span style=\" font-size:12pt;\">键盘输入中（常开）</span></p></body></html>"))
        self.voiceInput_btn.setToolTip(_translate("Homepage", "<html><head/><body><p><span style=\" font-size:12pt;\">点击开始语音输入</span></p></body></html>"))
        self.hintPanel_tb.setHtml(_translate("Homepage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cc0000;\">说明:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cc0000;\">         在使用键盘输入时，初始默认输入英文，此后可通过按shift键在中英文输入间切换。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cc0000;\">         语音输入支持中英文混合输入。</span></p></body></html>"))
